WebApp/WebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Pages
{
    public class IndexModel : PageModel
    {



        public void OnGet()
        {

        }
    }
}

WebApp/WebApp/Pages/Orden/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Entity;
using WBL;

namespace WebApp.Pages.Orden
{
    public class EditModel : PageModel
    {
        private readonly IOrdenService OrdenService;

        public EditModel(IOrdenService OrdenService)
        {
            this.OrdenService = OrdenService;
        }

        [BindProperty]
        public OrdenEntity Entity { get; set; } = new OrdenEntity();

        [BindProperty(SupportsGet = true)]
        public int? id { get; set; }


        public async Task<IActionResult> OnGet()
        {

            try
            {
                if (id.HasValue)
                {
                    Entity = await OrdenService.GetById(new() { IdOrden = id });
                }

                return Page();
            }
            catch (Exception ex)
            {

                return Content(ex.Message);
            }

        }

        public async Task<IActionResult> OnPostAsync()
        {

            try
            {
                if (Entity.IdOrden.HasValue)
                {
                    //Actualizar 
                    var result = await OrdenService.Update(Entity);

                    if (result.CodeError != 0) throw new Exception(result.MsgError);
                    TempData["Msg"] = "<input type='text' id='mens' value='Registro Modificado Correctamente' hidden></input><br/>";
                }
                else
                {
                    //Nuevo 
                    var result = await OrdenService.Create(Entity);

                    if (result.CodeError != 0) throw new Exception(result.MsgError);
                    TempData["Msg"] = "<input type='text' id='mens' value='Registro Agregado Correctamente' hidden></input><br/>";

                }

                return RedirectToPage("Grid");
            }



            catch (Exception ex)
            {

                return Content(ex.Message);
            }

        }




    }
}

WebApp/WebApp/Pages/Orden/Grid.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WBL;
using Entity;

namespace WebApp.Pages.Orden
{
    public class GridModel : PageModel
    {
        private readonly IOrdenService OrdenService;

        public GridModel(IOrdenService OrdenService)
        {
            this.OrdenService = OrdenService;
        }


        public IEnumerable<OrdenEntity> GridList { get; set; } = new List<OrdenEntity>();

        public string Mensaje { get; set; } = "";
        public async Task<IActionResult> OnGet()
        {

            try
            {
                GridList = await OrdenService.Get();

                if (TempData.ContainsKey("Msg"))
                {
                    Mensaje = TempData["Msg"] as string;
                }

                TempData.Clear();

                return Page();

            }
            catch (Exception ex)
            {

               return Content(ex.Message) ;
            }

        }

        public async Task<IActionResult> OnGetEliminar(int? id)
        {

            try
            {
                var result = await OrdenService.Delete( new OrdenEntity { IdOrden = id});

                if (result.CodeError!=0)
                {
                    throw new Exception(result.MsgError);
                }

                TempData["Msg"] = "<input type='text' id='mens' value='Registro Eliminado Correctamente' hidden></input> <br//>"; ;

                return Redirect("Grid");
        

            }
            catch (Exception ex)
            {

                return Content(ex.Message);
            }

        }
    }
}

WebApp/WebApp/Pages/Producto/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Entity;
using WBL;

namespace WebApp.Pages.Producto
{
    public class EditModel : PageModel
    {
        private readonly IProductoService ProductoService;

        public EditModel(IProductoService ProductoService)
        {
            this.ProductoService = ProductoService;
        }

        [BindProperty]
        public ProductoEntity Entity { get; set; } = new ProductoEntity();

        [BindProperty(SupportsGet = true)]
        public int? id { get; set; }


        public async Task<IActionResult> OnGet()
        {

            try
            {
                if (id.HasValue)
                {
                    Entity = await ProductoService.GetById(new() { IdProducto = id });
                }

                return Page();
            }
            catch (Exception ex)
            {

                return Content(ex.Message);
            }

        }

        public async Task<IActionResult> OnPostAsync()
        {

            try
            {
                if (Entity.IdProducto.HasValue)
                {
                    //Actualizar 
                    var result = await ProductoService.Update(Entity);

                    if (result.CodeError != 0) throw new Exception(result.MsgError);
                    TempData["Msg"] = "<input type='text' id='mens' value='Registro Modificado Correctamente' hidden></input><br/>";
                }
                else
                {
                    //Nuevo 
                    var result = await ProductoService.Create(Entity);

                    if (result.CodeError != 0) throw new Exception(result.MsgError);
                    TempData["Msg"] = "<input type='text' id='mens' value='Registro Agregado Correctamente' hidden></input><br/>";

                }

                return RedirectToPage("Grid");
            }



            catch (Exception ex)
            {

                return Content(ex.Message);
            }

        }




    }
}

WebApp/WebApp/Pages/Producto/Grid.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WBL;
using Entity;

namespace WebApp.Pages.Producto
{
    public class GridModel : PageModel
    {
        private readonly IProductoService ProductoService;

        public GridModel(IProductoService ProductoService)
        {
            this.ProductoService = ProductoService;
        }


        public IEnumerable<ProductoEntity> GridList { get; set; } = new List<ProductoEntity>();

        public string Mensaje { get; set; } = "";
        public async Task<IActionResult> OnGet()
        {

            try
            {
                GridList = await ProductoService.Get();

                if (TempData.ContainsKey("Msg"))
                {
                    Mensaje = TempData["Msg"] as string;
                }

                TempData.Clear();

                return Page();

            }
            catch (Exception ex)
            {

               return Content(ex.Message) ;
            }

        }

        public async Task<IActionResult> OnGetEliminar(int? id)
        {

            try
            {
                var result = await ProductoService.Delete( new ProductoEntity { IdProducto = id});

                if (result.CodeError!=0)
                {
                    throw new Exception(result.MsgError);
                }

                TempData["Msg"] = "<input type='text' id='mens' value='Registro Eliminado Correctamente' hidden></input> <br//>"; ;

                return Redirect("Grid");
        

            }
            catch (Exception ex)
            {

                return Content(ex.Message);
            }

        }
    }
}

WebApp/WebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Pagina Inicial";
}

<div id="" class="container">
    <button onclick="mostrar()" class="btn btn-outline-primary">
        Prueba
    </button>
</div>

<script>
    function mostrar()
    {
        Swal.fire({
            title: 'Continua',
            text: 'Seleccione Tipo Inquilino ',
            icon: 'info',
            confirmButtonText: 'Cool'
        })
    }
</script>

WebApp/WebApp/Pages/Orden/Edit.cshtml
@page
@model WebApp.Pages.Orden.EditModel
@{ }


<div id="AppEdit" class="container">
    <div class="card">
        <div class="card-header">
            @(Model.id.HasValue ? "Actualizar" : "Nuevo")
        </div>
        <div class="card-body">
            <form id="FormEdit" method="post">
                <input type="hidden" asp-for="Entity.IdOrden" />

                <div class="form-group mb-3">
                    <label for="Entity.IdProducto" class="form-label">IdProducto</label>
                    <input type="text" class="form-control" asp-for="Entity.IdProducto" maxlength="250" required>
                </div>
                <div class="form-group mb-3">
                    <label for="Entity.CantidadProducto" class="form-label">Cantidad</label>
                    <input type="text" class="form-control" asp-for="Entity.CantidadProducto" maxlength="250" required>
                </div>

                <div class="form-group form-check form-switch">
                    <input type="checkbox" class="form-check-input" asp-for="Entity.Estado" value="true">
                    <label for="Entity.Estado" class="form-check-label"> </label>
                </div>

                <div class="row">
                    <div class="col-4">
                        <button type="submit" class="btn btn-outline-primary">
                            @(Model.id.HasValue?"Actualizar":"Agregar")
                        </button>
                    </div>
                </div>

            </form>


        </div>
    </div>

</div>

@section Scripts{
<script>
    $(document).ready(function () {
        $('#FormEdit').bootstrapValidator({
            // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                Cantidad: {
                        stringLength: {
                            min: 1,
                            max: 10,
                            message: 'No puede ir vació'
                        },
                        regexp: {
                            regexp: /^[0-9]+$/,
                            message: 'Solo puede contener numeros'
                        }
                    }
                }
            }
        });
    });
</script>
    <script defer src="~/App/TipoInquilino/Edit.js"></script>

}

WebApp/WebApp/Pages/Orden/Grid.cshtml
@page
@model WebApp.Pages.Orden.GridModel
@{ }
<div class="container-fluid">

    <div class="card">
        <div class="card-header">
            Ordenes
        </div>
        <div class="card-body">
            <a class="btn btn-outline-primary" asp-page="Edit">
                <i class='bx bx-add-to-queue'></i>
            </a>
            <div class="row">
                <div class="col-12">
                    <table id="GridView" class="table table-bordered table table-striped table table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>ID Producto</th>
                                <th>Cantidad</th>
                                <th>Estado</th>
                            </tr>
                        </thead>
                        <tboby>
                            @foreach (var item in Model.GridList)
                            {
                <tr>
                    <td>@item.IdOrden</td>
                    <td>@item.IdProducto</td>
                    <td>@item.CantidadProducto</td>
                    <td>@(item.Estado ? "Activo": "Inactivo")</td>
                    <td>
                        <a class="btn btn-primary" asp-page="Edit" asp-route-id="@item.IdOrden"><i class='bx bx-edit-alt'></i></a>
                        <a class="btn btn-danger" asp-page-handler="Eliminar" asp-route-id="@item.IdOrden"><i class='bx bx-trash'></i></a>
                    </td>
                </tr>}
                        </tboby>
                    </table>

                </div>
            </div>



        </div>
    </div>
    @Html.Raw(Model.Mensaje)
</div>
@section Scripts{

    <script>
        $(document).ready(function () {
            var mens = document.getElementById("mens").value;
            console.log(mens);
            if (mens != "") {
                Swal.fire({
                    position: 'top-end',
                    icon: 'success',
                    title: mens,
                    showConfirmButton: false,
                    timer: 1500
                });
            }
            $('#GridView').DataTable();
            
            
            
        });
    </script>

    <script defer src="~/App/Orden/Grid.js"></script>

}

WebApp/WebApp/Pages/Producto/Edit.cshtml
@page
@model WebApp.Pages.Producto.EditModel
@{ }


<div id="AppEdit" class="container">
    <div class="card">
        <div class="card-header">
            @(Model.id.HasValue ? "Actualizar" : "Nuevo")
        </div>
        <div class="card-body">
            <form id="FormEdit" method="post">
                <input type="hidden" asp-for="Entity.IdProducto" />

                <div class="form-group mb-3">
                    <label for="Entity.NombreProducto" class="form-label">Nombre</label>
                    <input type="text" class="form-control" asp-for="Entity.NombreProducto" maxlength="250" required>
                </div>
                 <div class="form-group mb-3">
                    <label for="Entity.PrecioProducto" class="form-label">Precio</label>
                    <input type="text" class="form-control" asp-for="Entity.PrecioProducto" maxlength="250" required>
                </div>

                <div class="row">
                    <div class="col-4">
                        <button type="submit" class="btn btn-outline-primary">
                            @(Model.id.HasValue?"Actualizar":"Agregar")
                        </button>
                    </div>
                </div>

            </form>


        </div>
    </div>

</div>

@section Scripts{
<script>
    $(document).ready(function () {
        $('#FormEdit').bootstrapValidator({
            // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
            feedbackIcons: {
                valid: 'glyphicon glyphicon-ok',
                invalid: 'glyphicon glyphicon-remove',
                validating: 'glyphicon glyphicon-refresh'
            },
            fields: {
                Nombre: {
                    message: 'Nombre no valido',
                    validators: {
                        notEmpty: {
                            message: 'Nombre no puede ir vacio'
                        },
                        stringLength: {
                            min: 6,
                            max: 30,
                            message: 'El Nombre debe ser de 6 a 30 caracteres'
                        },
                        regexp: {
                            regexp: /^[a-zA-Z0-9]+$/,
                            message: 'El Nombre solo puede contener letras o numeros'
                        }
                    }
                }
            }
        });
    });
</script>
    <script defer src="~/App/Producto/Edit.js"></script>

}

WebApp/WebApp/Pages/Producto/Grid.cshtml
@page
@model WebApp.Pages.Producto.GridModel
@{ }
<div class="container-fluid">

    <div class="card">
        <div class="card-header">
            Producto
        </div>
        <div class="card-body">
            <a class="btn btn-outline-primary" asp-page="Edit">
                <i class='bx bx-add-to-queue'></i>
            </a>
            <div class="row">
                <div class="col-12">
                    <table id="GridView" class="table table-bordered table table-striped table table-hover">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nombre del producto</th>
                                <th>Precio</th>
                            </tr>
                        </thead>
                        <tboby>
                            @foreach (var item in Model.GridList)
                            {
                <tr>
                    <td>@item.IdProducto</td>
                    <td>@item.NombreProducto</td>
                    <td>@item.PrecioProducto</td>
                    <td>
                        <a class="btn btn-primary" asp-page="Edit" asp-route-id="@item.IdProducto"><i class='bx bx-edit-alt'></i></a>
                        <a class="btn btn-danger" asp-page-handler="Eliminar" asp-route-id="@item.IdProducto"><i class='bx bx-trash'></i></a>
                    </td>
                </tr>}
                        </tboby>
                    </table>

                </div>
            </div>



        </div>
    </div>
    @Html.Raw(Model.Mensaje)
</div>
@section Scripts{

    <script>
        $(document).ready(function () {
            var mens = document.getElementById("mens").value;
            console.log(mens);
            if (mens != "") {
                Swal.fire({
                    position: 'top-end',
                    icon: 'success',
                    title: mens,
                    showConfirmButton: false,
                    timer: 1500
                });
            }
            $('#GridView').DataTable();
            
            
            
        });
    </script>

    <script defer src="~/App/Producto/Grid.js"></script>

}

WebApp/WebApp/Pages/Shared/_HeaderPartial.cshtml
<style>
    [v-cloak] {
        display: none;
    }
</style>

<!--bootstrap-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.css" />
<!--bootstrap-->

<link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.23/datatables.min.css" />
<link href="~/Assets/Plugin/bvalidator/bootstrapValidator.css" rel="stylesheet" />
<link href="~/Assets/Plugin/sweetalert/sweetalert.css" rel="stylesheet" />


<!--Internet explorer solomente funciona para IE-->
<script src="~/Assets/Plugin/polyfill/polyfill.min.js"></script>
<script src="~/Assets/Plugin/jquery/jquery.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2"></script>

WebApp/WebApp/Pages/Shared/_HeaderTemplate.cshtml
<style>
    [v-cloak] {
        display: none;
    }
</style>

<link href="~/Assets/template/style.min.css" rel="stylesheet" />

<link type="text/css" rel="stylesheet" href="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.css" />

<link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.23/datatables.min.css" />
<link href="~/Assets/Plugin/bvalidator/bootstrapValidator.css" rel="stylesheet" />
<link href="~/Assets/Plugin/sweetalert/sweetalert.css" rel="stylesheet" />

<script src="~/Assets/Plugin/polyfill/polyfill.min.js"></script>

<script src="~/Assets/Plugin/jquery/jquery.js"></script>
<script src="~/Assets/Plugin/vue/vue.min.js"></script>

WebApp/WebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <base href="/" />
    <title>@ViewData["Title"] Examen 2 Progra VI</title>
   @await Html.PartialAsync("_HeaderPartial")
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:dodgerblue">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Examen 2 Programación 6</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-page="/Producto/Grid">Productos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-page="/Orden/Grid">Ordenes</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <br />
    @RenderBody()


    @await Html.PartialAsync("_ScriptsPartial")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApp/WebApp/Pages/Shared/_ScriptsPartial.cshtml
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

<script src="~/Assets/Plugin/sweetalert/sweetalert2@11.js"></script>
<script src="~/Assets/Plugin/axios/axios.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.23/datatables.min.js"></script>

<script src="~/Assets/Plugin/bvalidator/bootstrapValidator.js"></script>
<script src="~/Assets/Plugin/bvalidator/es_ES.js"></script>
<script src="~/Assets/Plugin/bvalidator/bv-validators.js"></script>
<script src="~/Assets/Plugin/bvalidator/FormValidateConfig.js"></script>

<script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.js"></script>
<!-- Load the following for BootstrapVueIcons support -->
<script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue-icons.min.js"></script>

<script src="~/Assets/Plugin/linq/linq.js"></script>

<script src="~/Assets/Plugin/sweetalert/SwalConfig.js"></script>


<script src="~/Scripts/AxiosProvider.js"></script>

WebApp/WebApp/Pages/Shared/_ScriptsTemplate.cshtml
<!--Template Scripts-->
<script src="~/Assets/template/bootstrap.bundle.min.js"></script>
<script src="~/Assets/template/app.min.js"></script>
<script src="~/Assets/template/app.init.js"></script>
<script src="~/Assets/template/app-style-switcher.js"></script>
<script src="~/Assets/template/perfect-scrollbar.jquery.min.js"></script>
<script src="~/Assets/template/sparkline.js"></script>
<script src="~/Assets/template/waves.js"></script>
<script src="~/Assets/template/sidebarmenu.js"></script>
<script src="~/Assets/template/feather.min.js"></script>
<script src="~/Assets/template/custom.min.js"></script>
<!--Template Scripts-->


<script src="~/Assets/Plugin/sweetalert/sweetalert2@11.js"></script>
<script src="~/Assets/Plugin/axios/axios.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.23/datatables.min.js"></script>

<script src="~/Assets/Plugin/bvalidator/bootstrapValidator.js"></script>
<script src="~/Assets/Plugin/bvalidator/es_ES.js"></script>
<script src="~/Assets/Plugin/bvalidator/bv-validators.js"></script>
<script src="~/Assets/Plugin/bvalidator/FormValidateConfig.js"></script>

<script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue.min.js"></script>
<!-- Load the following for BootstrapVueIcons support -->
<script src="//unpkg.com/bootstrap-vue@latest/dist/bootstrap-vue-icons.min.js"></script>

<script src="~/Assets/Plugin/linq/linq.js"></script>

<script src="~/Assets/Plugin/sweetalert/SwalConfig.js"></script>


<script src="~/Scripts/AxiosProvider.js"></script>